### ISSUE TITLE
Window leakage leads to app crash

### ISSUE THREAD

**Issue by NotQuiteAwake** [j0hnzzz/smart-air-conditioner#8]
Logcat detail
```
com.ota.jimmychen.ota E/WindowManager: android.view.WindowLeaked: Activity com.ota.jimmychen.ota.MainActivity has leaked window DecorView@b7c1857[] that was originally added here
        at android.view.ViewRootImpl.<init>(ViewRootImpl.java:485)
        at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:346)
        at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:92)
        at android.app.Dialog.show(Dialog.java:330)
        at android.app.AlertDialog$Builder.show(AlertDialog.java:1114)
        at com.ota.jimmychen.ota.MainActivity$3.onClick(MainActivity.java:118)
        at android.view.View.performClick(View.java:6256)
        at android.view.View$PerformClick.run(View.java:24701)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6541)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
```

**Comment by NotQuiteAwake** [comment]
Fixed.
